language: python
python:
  - "3.6"
branches:
  only:
  - ft-view_all_emails-#164691565
install:
  - pip install -r requirements.txt
script:
  - coverage run --omit */home/travis/virtualenv/* -m pytest
  - coverage report
  - coveralls