language: python
python:
  - "3.6"
branches:
  only:
  - ft-login_user-#164691327
install:
  - pip install -r requirements.txt
script:
  - coverage run --omit */home/travis/virtualenv/* -m pytest
  - coverage report
  - coveralls