language: python
python:
  - "3.6"
branches:
  only:
  - chall-3
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database epicmail_test;' -U postgres
script:
  - coverage run --omit */home/travis/virtualenv/* -m pytest
  - coverage report
  - coveralls