language: python
python:
  - "3.6"
branches:
  only:
  - ft-send_mail-#164691827
install:
  - pip install -r requirements.txt
script:
  - coverage run --omit */home/travis/virtualenv/* -m pytest
  - coverage report
  - coveralls